// Plan de Cuentas NIIF — Superintendencia de Compañías del Ecuador
// Fuente: Catálogo Único de Cuentas (CUC) Supercias — cuentas 1-52
// Generado automáticamente desde docs/pdf/PLAN DE CUENTAS.pdf
// 308 cuentas

const PLAN_SUPERCIAS = [
  { codigo: '1', nombre: "ACTIVO", nivel: 1, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '2', nombre: "PASIVO", nivel: 1, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '3', nombre: "PATRIMONIO NETO", nivel: 1, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '30', nombre: "PATRIMONIO ATRIBUIBLE A LOS PROPIETARIOS DE LA CONTROLADORA", nivel: 2, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '3', aceptaMovimiento: false },
  { codigo: '31', nombre: "PARTICIPACIÓN NO CONTROLADORA", nivel: 2, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '3', aceptaMovimiento: true },
  { codigo: '41', nombre: "INGRESOS DE ACTIVIDADES ORDINARIAS", nivel: 1, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '42', nombre: "GANANCIA BRUTA --> Subtotal A (41 - 51)", nivel: 1, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '43', nombre: "OTROS INGRESOS", nivel: 1, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '51', nombre: "COSTO DE VENTAS Y PRODUCCIÓN", nivel: 1, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '52', nombre: "GASTOS", nivel: 1, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: null, aceptaMovimiento: false },
  { codigo: '101', nombre: "ACTIVO CORRIENTE", nivel: 2, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '1', aceptaMovimiento: false },
  { codigo: '102', nombre: "ACTIVO NO CORRIENTE", nivel: 2, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '1', aceptaMovimiento: false },
  { codigo: '201', nombre: "PASIVO CORRIENTE", nivel: 2, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '2', aceptaMovimiento: false },
  { codigo: '202', nombre: "PASIVO NO CORRIENTE", nivel: 2, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '2', aceptaMovimiento: false },
  { codigo: '301', nombre: "CAPITAL", nivel: 3, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '30', aceptaMovimiento: false },
  { codigo: '302', nombre: "APORTES DE SOCIOS O ACCIONISTAS PARA FUTURA CAPITALIZACIÓN", nivel: 3, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '30', aceptaMovimiento: true },
  { codigo: '303', nombre: "PRIMA POR EMISION PRIMARIA DE ACCIONES", nivel: 3, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '30', aceptaMovimiento: true },
  { codigo: '304', nombre: "RESERVAS", nivel: 3, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '30', aceptaMovimiento: false },
  { codigo: '305', nombre: "OTROS RESULTADOS INTEGRALES", nivel: 3, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '30', aceptaMovimiento: false },
  { codigo: '306', nombre: "RESULTADOS ACUMULADOS", nivel: 3, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '30', aceptaMovimiento: false },
  { codigo: '307', nombre: "RESULTADOS DEL EJERCICIO", nivel: 3, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '30', aceptaMovimiento: false },
  { codigo: '4101', nombre: "VENTA DE BIENES", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4102', nombre: "PRESTACIÓN DE SERVICIOS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4103', nombre: "CONTRATOS DE CONSTRUCCIÓN", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4104', nombre: "SUBVENCIONES DEL GOBIERNO", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4105', nombre: "REGALÍAS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4106', nombre: "INTERESES", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: false },
  { codigo: '4107', nombre: "DIVIDENDOS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4108', nombre: "GANANCIA POR MEDICIÓN A VALOR RAZONABLE DE ACTIVOS BIOLÓGICOS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4109', nombre: "OTROS INGRESOS DE ACTIVIDADES ORDINARIAS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4110', nombre: "(-) DESCUENTO EN VENTAS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4111', nombre: "(-) DEVOLUCIONES EN VENTAS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4112', nombre: "(-) BONIFICACIÓN EN PRODUCTO", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4113', nombre: "(-) OTRAS REBAJAS COMERCIALES", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '41', aceptaMovimiento: true },
  { codigo: '4301', nombre: "DIVIDENDOS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '43', aceptaMovimiento: true },
  { codigo: '4302', nombre: "INTERESES FINANCIEROS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '43', aceptaMovimiento: true },
  { codigo: '4303', nombre: "GANANCIA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '43', aceptaMovimiento: true },
  { codigo: '4304', nombre: "VALUACIÓN DE INSTRUMENTOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN RESULTADOS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '43', aceptaMovimiento: true },
  { codigo: '4305', nombre: "OTRAS RENTAS", nivel: 2, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '43', aceptaMovimiento: true },
  { codigo: '5101', nombre: "MATERIALES UTILIZADOS O PRODUCTOS VENDIDOS", nivel: 2, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '51', aceptaMovimiento: false },
  { codigo: '5102', nombre: "(+) MANO DE OBRA DIRECTA", nivel: 2, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '51', aceptaMovimiento: false },
  { codigo: '5103', nombre: "(+) MANO DE OBRA INDIRECTA", nivel: 2, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '51', aceptaMovimiento: false },
  { codigo: '5104', nombre: "(+) OTROS COSTOS INDIRECTOS DE FABRICACIÓN", nivel: 2, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '51', aceptaMovimiento: false },
  { codigo: '5201', nombre: "GASTOS", nivel: 2, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '52', aceptaMovimiento: false },
  { codigo: '5202', nombre: "GASTOS", nivel: 2, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '52', aceptaMovimiento: false },
  { codigo: '5203', nombre: "GASTOS FINANCIEROS", nivel: 2, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '52', aceptaMovimiento: false },
  { codigo: '5204', nombre: "OTROS GASTOS", nivel: 2, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '52', aceptaMovimiento: false },
  { codigo: '10101', nombre: "EFECTIVO Y EQUIVALENTES AL EFECTIVO", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: true },
  { codigo: '10102', nombre: "ACTIVOS FINANCIEROS", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: false },
  { codigo: '10103', nombre: "INVENTARIOS", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: false },
  { codigo: '10104', nombre: "SERVICIOS Y OTROS PAGOS ANTICIPADOS", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: false },
  { codigo: '10105', nombre: "ACTIVOS POR IMPUESTOS CORRIENTES", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: false },
  { codigo: '10106', nombre: "ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA Y OPERACIONES DISCONTINUADAS", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: true },
  { codigo: '10107', nombre: "CONSTRUCCIONES EN PROCESO (NIC 11 Y SECC.23 PYMES)", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: true },
  { codigo: '10108', nombre: "OTROS ACTIVOS CORRIENTES", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '101', aceptaMovimiento: true },
  { codigo: '10201', nombre: "PROPIEDADES, PLANTA Y EQUIPO", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '102', aceptaMovimiento: false },
  { codigo: '10202', nombre: "PROPIEDADES DE INVERSIÓN", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '102', aceptaMovimiento: false },
  { codigo: '10203', nombre: "ACTIVOS BIOLOGICOS", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '102', aceptaMovimiento: false },
  { codigo: '10204', nombre: "ACTIVO INTANGIBLE", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '102', aceptaMovimiento: false },
  { codigo: '10205', nombre: "ACTIVOS POR IMPUESTOS DIFERIDOS", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '102', aceptaMovimiento: true },
  { codigo: '10206', nombre: "ACTIVOS FINANCIEROS NO CORRIENTES", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '102', aceptaMovimiento: false },
  { codigo: '10207', nombre: "OTROS ACTIVOS NO CORRIENTES", nivel: 3, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '102', aceptaMovimiento: false },
  { codigo: '20101', nombre: "PASIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADO", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20102', nombre: "PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIEROS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20103', nombre: "CUENTAS Y DOCUMENTOS POR PAGAR", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: false },
  { codigo: '20104', nombre: "OBLIGACIONES CON INSTITUCIONES FINANCIERAS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: false },
  { codigo: '20105', nombre: "PROVISIONES", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: false },
  { codigo: '20106', nombre: "PORCIÓN CORRIENTE DE OBLIGACIONES EMITIDAS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20107', nombre: "OTRAS OBLIGACIONES CORRIENTES", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: false },
  { codigo: '20108', nombre: "CUENTAS POR PAGAR DIVERSAS – RELACIONADAS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20109', nombre: "OTROS PASIVOS FINANCIEROS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20110', nombre: "ANTICIPOS DE CLIENTES", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20111', nombre: "PASIVOS DIRECTAMENTE ASOCIADOS CON LOS ACTIVOS NO CORRIENTES Y OPERACIONES DISCONTINUADAS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20112', nombre: "PORCIÓN CORRIENTE DE PROVISIONES POR BENEFICIOS A EMPLEADOS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: false },
  { codigo: '20113', nombre: "OTROS PASIVOS CORRIENTES", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '201', aceptaMovimiento: true },
  { codigo: '20201', nombre: "PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIERO", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: true },
  { codigo: '20202', nombre: "CUENTAS Y DOCUMENTOS POR PAGAR", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: false },
  { codigo: '20203', nombre: "OBLIGACIONES CON INSTITUCIONES FINANCIERAS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: false },
  { codigo: '20204', nombre: "CUENTAS POR PAGAR DIVERSAS / RELACIONADAS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: false },
  { codigo: '20205', nombre: "OBLIGACIONES EMITIDAS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: true },
  { codigo: '20206', nombre: "ANTICIPOS DE CLIENTES", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: true },
  { codigo: '20207', nombre: "PROVISIONES POR BENEFICIOS A EMPLEADOS", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: false },
  { codigo: '20208', nombre: "OTRAS PROVISIONES", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: true },
  { codigo: '20209', nombre: "PASIVO DIFERIDO", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: false },
  { codigo: '20210', nombre: "OTROS PASIVOS NO CORRIENTES", nivel: 3, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '202', aceptaMovimiento: true },
  { codigo: '30101', nombre: "CAPITAL SUSCRITO o ASIGNADO", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '301', aceptaMovimiento: true },
  { codigo: '30102', nombre: "(-) CAPITAL SUSCRITO NO PAGADO, ACCIONES EN TESORERÍA", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '301', aceptaMovimiento: true },
  { codigo: '30401', nombre: "RESERVA LEGAL", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '304', aceptaMovimiento: true },
  { codigo: '30402', nombre: "RESERVAS FACULTATIVA Y ESTATUTARIA", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '304', aceptaMovimiento: true },
  { codigo: '30501', nombre: "SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '305', aceptaMovimiento: true },
  { codigo: '30502', nombre: "SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '305', aceptaMovimiento: true },
  { codigo: '30503', nombre: "SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '305', aceptaMovimiento: true },
  { codigo: '30504', nombre: "OTROS SUPERAVIT POR REVALUACION", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '305', aceptaMovimiento: true },
  { codigo: '30601', nombre: "GANACIAS ACUMULADAS", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '306', aceptaMovimiento: true },
  { codigo: '30602', nombre: "(-) PÉRDIDAS ACUMULADAS", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '306', aceptaMovimiento: true },
  { codigo: '30603', nombre: "RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPCIÓN POR PRIMERA VEZ DE LAS NIIF", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '306', aceptaMovimiento: true },
  { codigo: '30604', nombre: "RESERVA DE CAPITAL", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '306', aceptaMovimiento: true },
  { codigo: '30605', nombre: "RESERVA POR DONACIONES", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '306', aceptaMovimiento: true },
  { codigo: '30606', nombre: "RESERVA POR VALUACIÓN", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '306', aceptaMovimiento: true },
  { codigo: '30607', nombre: "SUPERÁVIT POR REVALUACIÓN DE INVERSIONES", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '306', aceptaMovimiento: true },
  { codigo: '30701', nombre: "GANANCIA NETA DEL PERIODO", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '307', aceptaMovimiento: true },
  { codigo: '30702', nombre: "(-) PÉRDIDA NETA DEL PERIODO", nivel: 4, tipo: 'PATRIMONIO', naturaleza: 'CREDITO', codigoPadre: '307', aceptaMovimiento: true },
  { codigo: '410601', nombre: "INTERESES GENERADOS POR VENTAS A CRÉDITO", nivel: 3, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '4106', aceptaMovimiento: true },
  { codigo: '410602', nombre: "OTROS INTERESES GENERADOS", nivel: 3, tipo: 'INGRESO', naturaleza: 'CREDITO', codigoPadre: '4106', aceptaMovimiento: true },
  { codigo: '510101', nombre: "(+) INVENTARIO INICIAL DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510102', nombre: "(+) COMPRAS NETAS LOCALES DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510103', nombre: "(+) IMPORTACIONES DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510104', nombre: "(-) INVENTARIO FINAL DE BIENES NO PRODUCIDOS POR LA COMPAÑÍA", nivel: 3, tipo: 'COSTO', naturaleza: 'CREDITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510105', nombre: "(+) INVENTARIO INICIAL DE MATERIA PRIMA", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510106', nombre: "(+) COMPRAS NETAS LOCALES DE MATERIA PRIMA", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510107', nombre: "(+) IMPORTACIONES DE MATERIA PRIMA", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510108', nombre: "(-) INVENTARIO FINAL DE MATERIA PRIMA", nivel: 3, tipo: 'COSTO', naturaleza: 'CREDITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510109', nombre: "(+) INVENTARIO INICIAL DE PRODUCTOS EN PROCESO", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510110', nombre: "(-) INVENTARIO FINAL DE PRODUCTOS EN PROCESO", nivel: 3, tipo: 'COSTO', naturaleza: 'CREDITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510111', nombre: "(+) INVENTARIO INICIAL PRODUCTOS TERMINADOS", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510112', nombre: "(-) INVENTARIO FINAL DE PRODUCTOS TERMINADOS", nivel: 3, tipo: 'COSTO', naturaleza: 'CREDITO', codigoPadre: '5101', aceptaMovimiento: true },
  { codigo: '510201', nombre: "SUELDOS Y BENEFICIOS SOCIALES", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5102', aceptaMovimiento: true },
  { codigo: '510202', nombre: "GASTO PLANES DE BENEFICIOS A EMPLEADOS", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5102', aceptaMovimiento: true },
  { codigo: '510301', nombre: "SUELDOS Y BENEFICIOS SOCIALES", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5103', aceptaMovimiento: true },
  { codigo: '510302', nombre: "GASTO PLANES DE BENEFICIOS A EMPLEADOS", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5103', aceptaMovimiento: true },
  { codigo: '510401', nombre: "DEPRECIACIÓN PROPIEDADES, PLANTA Y EQUIPO", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '510402', nombre: "DETERIORO O PÉRDIDAS DE ACTIVOS BIOLÓGICOS", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '510403', nombre: "DETERIORO DE PROPIEDAD, PLANTA Y EQUIPO", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '510404', nombre: "EFECTO VALOR NETO DE REALIZACIÓN DE INVENTARIOS", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '510405', nombre: "GASTO POR GARANTÍAS EN VENTA DE PRODUCTOS O SERVICIOS", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '510406', nombre: "MANTENIMIENTO Y REPARACIONES", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '510407', nombre: "SUMINISTROS MATERIALES Y REPUESTOS", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '510408', nombre: "OTROS COSTOS DE PRODUCCIÓN", nivel: 3, tipo: 'COSTO', naturaleza: 'DEBITO', codigoPadre: '5104', aceptaMovimiento: true },
  { codigo: '520101', nombre: "SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520102', nombre: "APORTES A LA SEGURIDAD SOCIAL (incluido fondo de reserva)", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520103', nombre: "BENEFICIOS SOCIALES E INDEMNIZACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520104', nombre: "GASTO PLANES DE BENEFICIOS A EMPLEADOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520105', nombre: "HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520106', nombre: "REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520107', nombre: "HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520108', nombre: "MANTENIMIENTO Y REPARACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520109', nombre: "ARRENDAMIENTO OPERATIVO", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520110', nombre: "COMISIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520111', nombre: "PROMOCIÓN Y PUBLICIDAD", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520112', nombre: "COMBUSTIBLES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520113', nombre: "LUBRICANTES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520114', nombre: "SEGUROS Y REASEGUROS (primas y cesiones)", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520115', nombre: "TRANSPORTE", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520116', nombre: "GASTOS DE GESTIÓN (agasajos a accionistas, trabajadores y clientes)", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520117', nombre: "GASTOS DE VIAJE", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520118', nombre: "AGUA, ENERGÍA, LUZ Y TELECOMUNICACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520119', nombre: "NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520121', nombre: "DEPRECIACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: false },
  { codigo: '520122', nombre: "AMORTIZACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: false },
  { codigo: '520123', nombre: "GASTO DETERIORO", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: false },
  { codigo: '520124', nombre: "GASTOS POR CANTIDADES ANORMALES DE UTILIZACIÓN EN EL PROCESO DE PRODUCCIÓN", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: false },
  { codigo: '520125', nombre: "GASTO POR REESTRUCTURACIÓN", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520126', nombre: "VALOR NETO DE REALIZACIÓN DE INVENTARIOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520128', nombre: "OTROS GASTOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5201', aceptaMovimiento: true },
  { codigo: '520201', nombre: "SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520202', nombre: "APORTES A LA SEGURIDAD SOCIAL (incluido fondo de reserva)", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520203', nombre: "BENEFICIOS SOCIALES E INDEMNIZACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520204', nombre: "GASTO PLANES DE BENEFICIOS A EMPLEADOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520205', nombre: "HONORARIOS, COMISIONES Y DIETAS A PERSONAS NATURALES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520206', nombre: "REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520207', nombre: "HONORARIOS A EXTRANJEROS POR SERVICIOS OCASIONALES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520208', nombre: "MANTENIMIENTO Y REPARACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520209', nombre: "ARRENDAMIENTO OPERATIVO", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520210', nombre: "COMISIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520212', nombre: "COMBUSTIBLES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520213', nombre: "LUBRICANTES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520214', nombre: "SEGUROS Y REASEGUROS (primas y cesiones)", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520215', nombre: "TRANSPORTE", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520216', nombre: "GASTOS DE GESTIÓN (agasajos a accionistas, trabajadores y clientes)", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520217', nombre: "GASTOS DE VIAJE", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520218', nombre: "AGUA, ENERGÍA, LUZ Y TELECOMUNICACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520219', nombre: "NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520220', nombre: "IMPUESTOS, CONTRIBUCIONES Y OTROS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520221', nombre: "DEPRECIACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: false },
  { codigo: '520222', nombre: "AMORTIZACIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: false },
  { codigo: '520223', nombre: "GASTO DETERIORO", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: false },
  { codigo: '520224', nombre: "GASTOS POR CANTIDADES ANORMALES DE UTILIZACIÓN EN EL PROCESO DE PRODUCCIÓN", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: false },
  { codigo: '520225', nombre: "GASTO POR REESTRUCTURACIÓN", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520226', nombre: "VALOR NETO DE REALIZACIÓN DE INVENTARIOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520227', nombre: "GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS DIFERIDOS)", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520228', nombre: "OTROS GASTOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5202', aceptaMovimiento: true },
  { codigo: '520301', nombre: "INTERESES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5203', aceptaMovimiento: true },
  { codigo: '520302', nombre: "COMISIONES", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5203', aceptaMovimiento: true },
  { codigo: '520303', nombre: "GASTOS DE FINANCIAMIENTO DE ACTIVOS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5203', aceptaMovimiento: true },
  { codigo: '520304', nombre: "DIFERENCIA EN CAMBIO", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5203', aceptaMovimiento: true },
  { codigo: '520305', nombre: "OTROS GASTOS FINANCIEROS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5203', aceptaMovimiento: true },
  { codigo: '520401', nombre: "PERDIDA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5204', aceptaMovimiento: true },
  { codigo: '520402', nombre: "OTROS", nivel: 3, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '5204', aceptaMovimiento: true },
  { codigo: '1010201', nombre: "ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010202', nombre: "ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010203', nombre: "ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010204', nombre: "(-) PROVISION POR DETERIORO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010205', nombre: "DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES NO RELACIONADOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10102', aceptaMovimiento: false },
  { codigo: '1010206', nombre: "DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES RELACIONADOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010207', nombre: "OTRAS CUENTAS POR COBRAR RELACIONADAS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010208', nombre: "OTRAS CUENTAS POR COBRAR", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010209', nombre: "(-) PROVISIÓN CUENTAS INCOBRABLES Y DETERIORO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10102', aceptaMovimiento: true },
  { codigo: '1010301', nombre: "INVENTARIOS DE MATERIA PRIMA", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010302', nombre: "INVENTARIOS DE PRODUCTOS EN PROCESO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010303', nombre: "INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN EL PROCESO DE PRODUCCIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010304', nombre: "INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN LA PRESTACIÓN DE SERVICIO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010305', nombre: "INVENTARIOS DE PRODUCTOS TERMINADOS Y MERCADERIA EN ALMACÉN - PRODUCIDO POR LA COMPAÑÍA", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010306', nombre: "INVENTARIOS DE PRODUCTOS TERMINADOS Y MERCADERIA EN ALMACÉN - COMPRADO DE TERCEROS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010307', nombre: "MERCADERÍAS EN TRÁNSITO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010308', nombre: "OBRAS EN CONSTRUCCION", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010309', nombre: "OBRAS TERMINADAS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010310', nombre: "MATERIALES O BIENES PARA LA CONSTRUCCIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010311', nombre: "INVENTARIOS REPUESTOS, HERRAMIENTAS Y ACCESORIOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010312', nombre: "OTROS INVENTARIOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010313', nombre: "(-) PROVISIÓN POR VALOR NETO DE REALIZACIÓN Y OTRAS PÉRDIDAS EN EL INVENTARIO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10103', aceptaMovimiento: true },
  { codigo: '1010401', nombre: "SEGUROS PAGADOS POR ANTICIPADO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10104', aceptaMovimiento: true },
  { codigo: '1010402', nombre: "ARRIENDOS PAGADOS POR ANTICIPADO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10104', aceptaMovimiento: true },
  { codigo: '1010403', nombre: "ANTICIPOS A PROVEEDORES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10104', aceptaMovimiento: true },
  { codigo: '1010404', nombre: "OTROS ANTICIPOS ENTREGADOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10104', aceptaMovimiento: true },
  { codigo: '1010501', nombre: "CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA (IVA)", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10105', aceptaMovimiento: true },
  { codigo: '1010502', nombre: "CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA ( I. R.)", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10105', aceptaMovimiento: true },
  { codigo: '1010503', nombre: "ANTICIPO DE IMPUESTO A LA RENTA", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10105', aceptaMovimiento: true },
  { codigo: '1020101', nombre: "TERRENOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020102', nombre: "EDIFICIOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020103', nombre: "CONTRUCCIONES EN CURSO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020104', nombre: "INSTALACIONES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020105', nombre: "MUEBLES Y ENSERES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020106', nombre: "MAQUINARIA Y EQUIPO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020107', nombre: "NAVES, AERONAVES, BARCAZAS Y SIMILARES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020108', nombre: "EQUIPO DE COMPUTACIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020109', nombre: "VEHÍCULOS, EQUIPOS DE TRANSPORTE Y EQUIPO CAMINERO MÓVIL", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020110', nombre: "OTROS PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020111', nombre: "REPUESTOS Y HERRAMIENTAS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020112', nombre: "(-) DEPRECIACIÓN ACUMULADA PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020113', nombre: "(-) DETERIORO ACUMULADO DE PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10201', aceptaMovimiento: true },
  { codigo: '1020114', nombre: "ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10201', aceptaMovimiento: false },
  { codigo: '1020201', nombre: "TERRENOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10202', aceptaMovimiento: true },
  { codigo: '1020202', nombre: "EDIFICIOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10202', aceptaMovimiento: true },
  { codigo: '1020203', nombre: "(-) DEPRECIACION ACUMULADA DE PROPIEDADES DE INVERSIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10202', aceptaMovimiento: true },
  { codigo: '1020204', nombre: "(-) DETERIORO ACUMULADO DE PROPIEDADES DE INVERSIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10202', aceptaMovimiento: true },
  { codigo: '1020301', nombre: "ANIMALES VIVOS EN CRECIMIENTO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10203', aceptaMovimiento: true },
  { codigo: '1020302', nombre: "ANIMALES VIVOS EN PRODUCCIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10203', aceptaMovimiento: true },
  { codigo: '1020303', nombre: "PLANTAS EN CRECIMIENTO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10203', aceptaMovimiento: true },
  { codigo: '1020304', nombre: "PLANTAS EN PRODUCCIÓN", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10203', aceptaMovimiento: true },
  { codigo: '1020305', nombre: "(-) DEPRECIACIÓN ACUMULADA DE ACTIVOS BIOLÓGICOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10203', aceptaMovimiento: true },
  { codigo: '1020306', nombre: "(-) DETERIORO ACUMULADO DE ACTIVOS BIOLÓGICOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10203', aceptaMovimiento: true },
  { codigo: '1020401', nombre: "PLUSVALÍAS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10204', aceptaMovimiento: true },
  { codigo: '1020402', nombre: "MARCAS, PATENTES, DERECHOS DE LLAVE, CUOTAS PATRIMONIALES Y OTROS SIMILARES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10204', aceptaMovimiento: true },
  { codigo: '1020403', nombre: "ACTIVOS DE EXPLORACION Y EXPLOTACION", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10204', aceptaMovimiento: true },
  { codigo: '1020404', nombre: "(-) AMORTIZACIÓN ACUMULADA DE ACTIVO INTANGIBLE", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10204', aceptaMovimiento: true },
  { codigo: '1020405', nombre: "(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10204', aceptaMovimiento: true },
  { codigo: '1020406', nombre: "OTROS INTANGIBLES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10204', aceptaMovimiento: true },
  { codigo: '1020601', nombre: "ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10206', aceptaMovimiento: true },
  { codigo: '1020602', nombre: "(-) PROVISIÓN POR DETERIORO DE ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10206', aceptaMovimiento: true },
  { codigo: '1020603', nombre: "DOCUMENTOS Y CUENTAS POR COBRAR", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10206', aceptaMovimiento: true },
  { codigo: '1020604', nombre: "(-) PROVISIÓN CUENTAS INCOBRABLES DE ACTIVOS FINANCIEROS NO CORRIENTES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10206', aceptaMovimiento: true },
  { codigo: '1020701', nombre: "INVERSIONES SUBSIDIARIAS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10207', aceptaMovimiento: true },
  { codigo: '1020702', nombre: "INVERSIONES ASOCIADAS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10207', aceptaMovimiento: true },
  { codigo: '1020703', nombre: "INVERSIONES NEGOCIOS CONJUNTOS", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10207', aceptaMovimiento: true },
  { codigo: '1020704', nombre: "OTRAS INVERSIONES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10207', aceptaMovimiento: true },
  { codigo: '1020705', nombre: "(-) PROVISIÓN VALUACIÓN DE INVERSIONES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '10207', aceptaMovimiento: true },
  { codigo: '1020706', nombre: "OTROS ACTIVOS NO CORRIENTES", nivel: 4, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '10207', aceptaMovimiento: true },
  { codigo: '2010301', nombre: "LOCALES", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20103', aceptaMovimiento: true },
  { codigo: '2010302', nombre: "DEL EXTERIOR", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20103', aceptaMovimiento: true },
  { codigo: '2010401', nombre: "LOCALES", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20104', aceptaMovimiento: true },
  { codigo: '2010402', nombre: "DEL EXTERIOR", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20104', aceptaMovimiento: true },
  { codigo: '2010501', nombre: "LOCALES", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20105', aceptaMovimiento: true },
  { codigo: '2010502', nombre: "DEL EXTERIOR", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20105', aceptaMovimiento: true },
  { codigo: '2010701', nombre: "CON LA ADMINISTRACIÓN TRIBUTARIA", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20107', aceptaMovimiento: true },
  { codigo: '2010702', nombre: "IMPUESTO A LA RENTA POR PAGAR DEL EJERCICIO", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20107', aceptaMovimiento: true },
  { codigo: '2010703', nombre: "CON EL IESS", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20107', aceptaMovimiento: true },
  { codigo: '2010704', nombre: "POR BENEFICIOS DE LEY A EMPLEADOS", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20107', aceptaMovimiento: true },
  { codigo: '2010705', nombre: "PARTICIPACIÓN TRABAJADORES POR PAGAR DEL EJERCICIO", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20107', aceptaMovimiento: true },
  { codigo: '2010706', nombre: "DIVIDENDOS POR PAGAR", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20107', aceptaMovimiento: true },
  { codigo: '2011201', nombre: "JUBILACIÓN PATRONAL", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20112', aceptaMovimiento: true },
  { codigo: '2011202', nombre: "OTROS BENEFICIOS A LARGO PLAZO PARA LOS EMPLEADOS", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20112', aceptaMovimiento: true },
  { codigo: '2020201', nombre: "LOCALES", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20202', aceptaMovimiento: true },
  { codigo: '2020202', nombre: "DEL EXTERIOR", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20202', aceptaMovimiento: true },
  { codigo: '2020301', nombre: "LOCALES", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20203', aceptaMovimiento: true },
  { codigo: '2020302', nombre: "DEL EXTERIOR", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20203', aceptaMovimiento: true },
  { codigo: '2020401', nombre: "LOCALES", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20204', aceptaMovimiento: true },
  { codigo: '2020402', nombre: "DEL EXTERIOR", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20204', aceptaMovimiento: true },
  { codigo: '2020701', nombre: "JUBILACIÓN PATRONAL", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20207', aceptaMovimiento: true },
  { codigo: '2020702', nombre: "OTROS BENEFICIOS NO CORRIENTES PARA LOS EMPLEADOS", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20207', aceptaMovimiento: true },
  { codigo: '2020901', nombre: "INGRESOS DIFERIDOS", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20209', aceptaMovimiento: true },
  { codigo: '2020902', nombre: "PASIVOS POR IMPUESTOS DIFERIDOS", nivel: 4, tipo: 'PASIVO', naturaleza: 'CREDITO', codigoPadre: '20209', aceptaMovimiento: true },
  { codigo: '52012101', nombre: "PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520121', aceptaMovimiento: true },
  { codigo: '52012102', nombre: "PROPIEDADES DE INVERSIÓN", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520121', aceptaMovimiento: true },
  { codigo: '52012201', nombre: "INTANGIBLES", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520122', aceptaMovimiento: true },
  { codigo: '52012202', nombre: "OTROS ACTIVOS", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520122', aceptaMovimiento: true },
  { codigo: '52012301', nombre: "PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520123', aceptaMovimiento: true },
  { codigo: '52012306', nombre: "OTROS ACTIVOS", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520123', aceptaMovimiento: true },
  { codigo: '52012401', nombre: "MANO DE OBRA", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520124', aceptaMovimiento: true },
  { codigo: '52012402', nombre: "MATERIALES", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520124', aceptaMovimiento: true },
  { codigo: '52012403', nombre: "COSTOS DE PRODUCCIÓN", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520124', aceptaMovimiento: true },
  { codigo: '52022101', nombre: "PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520221', aceptaMovimiento: true },
  { codigo: '52022102', nombre: "PROPIEDADES DE INVERSIÓN", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520221', aceptaMovimiento: true },
  { codigo: '52022201', nombre: "INTANGIBLES", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520222', aceptaMovimiento: true },
  { codigo: '52022202', nombre: "OTROS ACTIVOS", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520222', aceptaMovimiento: true },
  { codigo: '52022301', nombre: "PROPIEDADES, PLANTA Y EQUIPO", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520223', aceptaMovimiento: true },
  { codigo: '52022302', nombre: "INVENTARIOS", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520223', aceptaMovimiento: true },
  { codigo: '52022303', nombre: "INSTRUMENTOS FINANCIEROS", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520223', aceptaMovimiento: true },
  { codigo: '52022304', nombre: "INTANGIBLES", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520223', aceptaMovimiento: true },
  { codigo: '52022305', nombre: "CUENTAS POR COBRAR", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520223', aceptaMovimiento: true },
  { codigo: '52022306', nombre: "OTROS ACTIVOS", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520223', aceptaMovimiento: true },
  { codigo: '52022401', nombre: "MANO DE OBRA", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520224', aceptaMovimiento: true },
  { codigo: '52022402', nombre: "MATERIALES", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520224', aceptaMovimiento: true },
  { codigo: '52022403', nombre: "COSTOS DE PRODUCCIÓN", nivel: 4, tipo: 'GASTO', naturaleza: 'DEBITO', codigoPadre: '520224', aceptaMovimiento: true },
  { codigo: '101020501', nombre: "DE ACTIVIDADES ORDINARIAS QUE GENEREN INTERESES", nivel: 5, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '1010205', aceptaMovimiento: true },
  { codigo: '101020502', nombre: "DE ACTIVIDADES ORDINARIAS QUE NO GENEREN INTERESES", nivel: 5, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '1010205', aceptaMovimiento: true },
  { codigo: '102011401', nombre: "ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN", nivel: 5, tipo: 'ACTIVO', naturaleza: 'DEBITO', codigoPadre: '1020114', aceptaMovimiento: true },
  { codigo: '102011402', nombre: "(-) AMORTIZACIÓN ACUMULADA DE ACTIVOS DE EXLORACIÓN Y EXPLOTACIÓN", nivel: 5, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '1020114', aceptaMovimiento: true },
  { codigo: '102011403', nombre: "(-) DETERIORO ACUMULADO DE ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN", nivel: 5, tipo: 'ACTIVO', naturaleza: 'CREDITO', codigoPadre: '1020114', aceptaMovimiento: true },
];

async function sembrarPlanSupercias(db, empresaId, overwriteExisting = false) {
  let creadas = 0;
  let actualizadas = 0;

  for (const cuenta of PLAN_SUPERCIAS) {
    const data = { ...cuenta, empresaId, activo: true };
    const existente = await db.plan_cuentas.findFirst({ where: { empresaId, codigo: cuenta.codigo } });
    if (existente) {
      if (overwriteExisting) {
        await db.plan_cuentas.update({ where: { id: existente.id }, data });
        actualizadas++;
      }
    } else {
      await db.plan_cuentas.create({ data });
      creadas++;
    }
  }

  return { creadas, actualizadas, total: PLAN_SUPERCIAS.length };
}

module.exports = { sembrarPlanSupercias, PLAN_SUPERCIAS };
